#!/bin/bash
#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

domain="$(ynh_app_setting_get --app=$app --key=domain)"

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

get__redirect_path() {
    ynh_app_setting_get --app=$app --key=redirect_path
}

set__redirect_path() {
    old_path="$(ynh_app_setting_get --app=$app --key=redirect_path)"
    
    ynh_replace_special_string --match_string="$old_path" --replace_string="$redirect_path" --target_file="/etc/nginx/conf.d/$domain.d/$app.conf"
    
    ynh_app_setting_set --app=$app --key=redirect_path --value=$redirect_path
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
